In [1]:
import numpy as np
import pandas as pd
from scoring import score_event

drivers = pd.read_csv("../00_source_data/salaries_pre_race0.csv")
drivers

,held,type,driver_name,driver_team,starting_salary,eight_race_average,qualifying_position,finishing_position
0,0,driver,M. Verstappen,RBR,30.0,1,2.0,2.0
1,0,driver,G. Russell,MER,28.7,2,1.0,1.0
2,0,driver,L. Norris,MCL,27.4,3,3.0,3.0
3,0,driver,O. Piastri,MCL,26.1,4,4.0,4.0
4,1,driver,K. Antonelli,MER,24.8,5,22.0,6.0
5,0,driver,C. Leclerc,FER,23.5,6,5.0,5.0
6,0,driver,F. Alonso,AMR,22.2,7,21.0,21.0
7,1,driver,L. Hamilton,FER,20.9,8,6.0,6.0
8,0,driver,I. Hadjar,RBR,19.6,9,8.0,8.0
9,0,driver,P. Gasly,ALP,18.3,10,9.0,9.0
10,0,driver,L. Stroll,AMR,17.0,11,20.0,20.0
11,0,driver,C. Sainz Jr,WIL,15.7,12,19.0,19.0
12,0,driver,L. Lawson,RBS,14.4,13,13.0,13.0
13,0,driver,A. Albon,WIL,13.1,14,18.0,18.0
14,0,driver,N. Hulkenberg,AUD,11.8,15,15.0,15.0
15,0,driver,G. Bortoleto,AUD,10.5,16,16.0,16.0
16,1,driver,O. Bearman,HAS,9.2,17,11.0,11.0
17,1,driver,E. Ocon,HAS,7.9,18,10.0,10.0
18,0,driver,V. Bottas,CAD,4.7,19,16.0,16.0
19,0,driver,S. Perez,CAD,4.7,20,17.0,17.0
20,1,driver,F. Colapinto,ALP,4.7,21,14.0,14.0
21,0,driver,A. Lindblad,RBS,4.6,22,15.0,15.0
22,0,team,MER,NaN,28.5,1,NaN,NaN
23,0,team,MCL,NaN,28.5,2,NaN,NaN
24,0,team,RBR,NaN,25.0,3,NaN,NaN
25,0,team,FER,NaN,22.5,4,NaN,NaN
26,0,team,AMR,NaN,20.0,5,NaN,NaN
27,0,team,WIL,NaN,17.5,6,NaN,NaN
28,0,team,RBS,NaN,15.0,7,NaN,NaN
29,0,team,ALP,NaN,12.5,8,NaN,NaN
30,0,team,AUD,NaN,10.0,9,NaN,NaN
31,0,team,CAD,NaN,7.5,10,NaN,NaN
32,1,team,HAS,NaN,5.0,11,NaN,NaN

In [2]:
updated = score_event(drivers)
updated

total points: 791
total salary change: 10.8

,held,type,driver_name,driver_team,starting_salary,eight_race_average,qualifying_position,finishing_position,pts_qualifying,pts_race,pts_overtake,pts_improvement,pts_completion,pts_teammate,points_earned,salary_after_event,salary_change
0,0,driver,M. Verstappen,RBR,30.0,1,2.0,2.0,48,97,0.0,0.0,12.0,5.0,162.0,30.5,0.5
1,0,driver,G. Russell,MER,28.7,2,1.0,1.0,50,100,0.0,0.0,12.0,5.0,167.0,30.0,1.3
2,0,driver,L. Norris,MCL,27.4,3,3.0,3.0,46,94,0.0,0.0,12.0,2.0,154.0,28.2,0.8
3,0,driver,O. Piastri,MCL,26.1,4,4.0,4.0,44,91,0.0,0.0,12.0,0.0,147.0,26.4,0.3
4,1,driver,K. Antonelli,MER,24.8,5,22.0,6.0,8,85,48.0,0.0,12.0,0.0,153.0,25.8,1.0
5,0,driver,C. Leclerc,FER,23.5,6,5.0,5.0,42,88,0.0,0.0,12.0,2.0,144.0,24.1,0.6
6,0,driver,F. Alonso,AMR,22.2,7,21.0,21.0,10,40,0.0,0.0,12.0,0.0,62.0,20.2,-2.0
7,1,driver,L. Hamilton,FER,20.9,8,6.0,6.0,40,85,0.0,2.0,12.0,0.0,139.0,21.7,0.8
8,0,driver,I. Hadjar,RBR,19.6,9,8.0,8.0,36,79,0.0,0.0,12.0,0.0,127.0,19.9,0.3
9,0,driver,P. Gasly,ALP,18.3,10,9.0,9.0,34,76,0.0,0.0,12.0,5.0,127.0,18.6,0.3
10,0,driver,L. Stroll,AMR,17.0,11,20.0,20.0,12,43,0.0,0.0,12.0,2.0,69.0,15.0,-2.0
11,0,driver,C. Sainz Jr,WIL,15.7,12,19.0,19.0,14,46,0.0,0.0,12.0,0.0,72.0,13.7,-2.0
12,0,driver,L. Lawson,RBS,14.4,13,13.0,13.0,26,64,0.0,0.0,12.0,2.0,104.0,14.1,-0.3
13,0,driver,A. Albon,WIL,13.1,14,18.0,18.0,16,49,0.0,0.0,12.0,2.0,79.0,11.2,-1.9
14,0,driver,N. Hulkenberg,AUD,11.8,15,15.0,15.0,22,58,0.0,0.0,12.0,2.0,94.0,11.7,-0.1
15,0,driver,G. Bortoleto,AUD,10.5,16,16.0,16.0,20,55,0.0,0.0,12.0,0.0,87.0,10.0,-0.5
16,1,driver,O. Bearman,HAS,9.2,17,11.0,11.0,30,70,0.0,12.0,12.0,0.0,124.0,11.2,2.0
17,1,driver,E. Ocon,HAS,7.9,18,10.0,10.0,32,73,0.0,20.0,12.0,2.0,139.0,9.9,2.0
18,0,driver,V. Bottas,CAD,4.7,19,16.0,16.0,20,55,0.0,4.0,12.0,2.0,93.0,6.0,1.3
19,0,driver,S. Perez,CAD,4.7,20,17.0,17.0,18,52,0.0,4.0,12.0,0.0,86.0,5.2,0.5
20,1,driver,F. Colapinto,ALP,4.7,21,14.0,14.0,24,61,0.0,16.0,12.0,0.0,113.0,6.7,2.0
21,0,driver,A. Lindblad,RBS,4.6,22,15.0,15.0,22,58,0.0,16.0,12.0,0.0,108.0,6.6,2.0
22,0,team,MER,NaN,28.5,1,NaN,NaN,39,110,NaN,NaN,NaN,NaN,149.0,27.0,-1.5
23,0,team,MCL,NaN,28.5,2,NaN,NaN,55,110,NaN,NaN,NaN,NaN,165.0,28.8,0.3
24,0,team,RBR,NaN,25.0,3,NaN,NaN,52,104,NaN,NaN,NaN,NaN,156.0,25.5,0.5
25,0,team,FER,NaN,22.5,4,NaN,NaN,51,102,NaN,NaN,NaN,NaN,153.0,23.0,0.5
26,0,team,AMR,NaN,20.0,5,NaN,NaN,21,42,NaN,NaN,NaN,NaN,63.0,17.0,-3.0
27,0,team,WIL,NaN,17.5,6,NaN,NaN,25,50,NaN,NaN,NaN,NaN,75.0,14.8,-2.7
28,0,team,RBS,NaN,15.0,7,NaN,NaN,34,68,NaN,NaN,NaN,NaN,102.0,14.9,-0.1
29,0,team,ALP,NaN,12.5,8,NaN,NaN,39,78,NaN,NaN,NaN,NaN,117.0,13.6,1.1
30,0,team,AUD,NaN,10.0,9,NaN,NaN,31,62,NaN,NaN,NaN,NaN,93.0,10.4,0.4
31,0,team,CAD,NaN,7.5,10,NaN,NaN,29,58,NaN,NaN,NaN,NaN,87.0,7.9,0.4
32,1,team,HAS,NaN,5.0,11,NaN,NaN,41,82,NaN,NaN,NaN,NaN,123.0,8.0,3.0

In [3]:
updated.loc[updated["held"] == 1, ["driver_name", "points_earned", "salary_change"]]

     driver_name  points_earned  salary_change
4   K. Antonelli          153.0            1.0
7    L. Hamilton          139.0            0.8
16    O. Bearman          124.0            2.0
17       E. Ocon          139.0            2.0
20  F. Colapinto          113.0            2.0
32           HAS          123.0            3.0

In [4]:
updated[updated["held"] == 1]

,held,type,driver_name,driver_team,starting_salary,eight_race_average,qualifying_position,finishing_position,pts_qualifying,pts_race,pts_overtake,pts_improvement,pts_completion,pts_teammate,points_earned,salary_after_event,salary_change
4,1,driver,K. Antonelli,MER,24.8,5,22.0,6.0,8,85,48.0,0.0,12.0,0.0,153.0,25.8,1.0
7,1,driver,L. Hamilton,FER,20.9,8,6.0,6.0,40,85,0.0,2.0,12.0,0.0,139.0,21.7,0.8
16,1,driver,O. Bearman,HAS,9.2,17,11.0,11.0,30,70,0.0,12.0,12.0,0.0,124.0,11.2,2.0
17,1,driver,E. Ocon,HAS,7.9,18,10.0,10.0,32,73,0.0,20.0,12.0,2.0,139.0,9.9,2.0
20,1,driver,F. Colapinto,ALP,4.7,21,14.0,14.0,24,61,0.0,16.0,12.0,0.0,113.0,6.7,2.0
32,1,team,HAS,NaN,5.0,11,NaN,NaN,41,82,NaN,NaN,NaN,NaN,123.0,8.0,3.0